### ISSUE TITLE
in handle_text output = host.agent.handle_text(message, sender_id=sender_id) AttributeError: 'NoneType' object has no attribute 'handle_text'

### ISSUE THREAD

**Issue by AnikaTabassum** [danielgolabek/RasaHost#7]
![Screenshot from 2020-03-03 12-33-33](https://user-images.githubusercontent.com/35559892/75749112-3cab2180-5d4b-11ea-8c82-0d1be739cd9d.png)
Hi... I am trying to use rasahost. But whenever I chat, I try to send a message then I get the following error **  File "/Desktop/RasaHost-master/src/RasaHost/RasaHost/services/conversations_service.py", line 89, in handle_text
    output = host.agent.handle_text(message, sender_id=sender_id)
AttributeError: 'NoneType' object has no attribute 'handle_text'
**

and one more thing, memoization policy does not show anything. I have attached the screenshots. 
![Screenshot from 2020-03-03 12-31-40](https://user-images.githubusercontent.com/35559892/75749043-0d94b000-5d4b-11ea-8d90-1fc54eebfcef.png)

thanks!

**Comment by peisong0109** [comment]
I got the same problem. Have you solved?

**Comment by AnikaTabassum** [comment]
> I got the same problem. Have you solved?

I have solved the chat module by adding agent 
agent= Agent.load("path/to/the/models/all")
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
but unfortunately couldn't solve the memoizaion policy issue :(
